// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWnf_V2QTggKrCx6gpVkoZQvKOYJY5Rpg',
    appId: '1:1036053921134:web:7fce9d9c2df9a920a4957f',
    messagingSenderId: '1036053921134',
    projectId: 'new-tripple',
    authDomain: 'new-tripple.firebaseapp.com',
    storageBucket: 'new-tripple.firebasestorage.app',
    measurementId: 'G-3RFFBNM0KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGZq12RjPfc4EIBvlQuvy1PXlb2vVmMsE',
    appId: '1:1036053921134:android:a9b5c6a2d196b958a4957f',
    messagingSenderId: '1036053921134',
    projectId: 'new-tripple',
    storageBucket: 'new-tripple.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Zol0RUIq3UyQKm9yS4cxR4USmd8iI38',
    appId: '1:1036053921134:ios:cf92d290b3cd4615a4957f',
    messagingSenderId: '1036053921134',
    projectId: 'new-tripple',
    storageBucket: 'new-tripple.firebasestorage.app',
    androidClientId: '1036053921134-d51psrs1cc6cnqm4or92cffo470o0dh1.apps.googleusercontent.com',
    iosClientId: '1036053921134-9dr0qq727k9it9h1hc54hfo6o4n4t0ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.newTripple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlKefsKZJV8TRaW-WY24ne8ESK_QvUG38',
    appId: '1:454701744658:ios:4216f61288dfb5b4874ecb',
    messagingSenderId: '454701744658',
    projectId: 'tripple-89772',
    storageBucket: 'tripple-89772.firebasestorage.app',
    androidClientId: '454701744658-gc1dvu554h75ftcgpuosqds0qbag3bek.apps.googleusercontent.com',
    iosClientId: '454701744658-jml7pfq3ecla5ss4logg2oo78rip5p2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.newTripple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHlVsE7onKXDOazhkHZK3nANHCS-i92oQ',
    appId: '1:454701744658:web:eb636015785f1c84874ecb',
    messagingSenderId: '454701744658',
    projectId: 'tripple-89772',
    authDomain: 'tripple-89772.firebaseapp.com',
    storageBucket: 'tripple-89772.firebasestorage.app',
    measurementId: 'G-6XNH22TTR0',
  );
}